name: netx-hydro

channels:
  - esri
  - conda-forge
  - defaults

dependencies:
  - arcgis==1.7.1  
  - cookiecutter
  - dask
  - mkdocs
  - nodejs
  - pillow
  - pyarrow
  - pylint
  - pytest
  - python-dotenv
  - scipy
  - scikit-learn
  - seaborn
  - shapely
  - swifter
  - tqdm
  - pip:
    - azure-storage-blob
    - ipykernel
    - sphinx